# Generated by Django 3.1 on 2021-05-15 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('mobile', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('is_checked', models.BooleanField(default=False)),
                ('verified_by', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('patient', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='info', serialize=False, to='patients.details')),
                ('message', models.TextField(default=None)),
                ('doctor_name', models.CharField(max_length=50)),
                ('client_name', models.CharField(max_length=50)),
            ],
        ),
    ]
