# Generated by Django 3.1 on 2021-05-23 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('mobile', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'other')], default='male', max_length=6)),
                ('age', models.PositiveIntegerField(default=18)),
                ('saturation_level', models.FloatField(default=80)),
                ('heart_rate', models.FloatField(default=130)),
                ('is_checked', models.BooleanField(default=False)),
                ('symptoms', models.TextField(default=None, max_length=150)),
                ('Form_date', models.DateField(default='2001-04-12')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('patient', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='info', serialize=False, to='patients.details')),
                ('message', models.TextField(default=None)),
                ('doctor_name', models.CharField(max_length=50)),
                ('client_name', models.CharField(max_length=50)),
            ],
        ),
    ]
