# Generated by Django 3.2 on 2021-05-15 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='message',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='patients.details'),
        ),
    ]
