# Generated by Django 3.1 on 2021-05-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_details_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='mobile',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
