# Generated by Django 3.2 on 2021-05-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20210521_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='symptoms',
            field=models.TextField(default=None, max_length=150),
        ),
    ]
