# Generated by Django 3.2 on 2021-05-15 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_rename_report_report_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='info', to='patients.details'),
        ),
    ]
